config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'events#index'

  resources :users do
    post 'send_email_confirmation' => 'users#send_email_confirmation'
  end

  resources :clubs do
    resources :comments
  end

  resources :events do
    resources :comments
  end

  resources :friendships

  # Messages
  resources :messages, only: [:new, :create, :show, :destroy]
  get 'inbox' => 'messages#inbox'
  get 'sentbox' => 'messages#sentbox'
  # Authorization
  post 'login_with_email' => 'sessions#login_with_email'
  get '/auth/:provider/callback' => 'sessions#login_with_oauth'
  post '/auth/:provider/callback' => 'sessions#login_with_oauth'
  # resources :sessions
  get 'logout' => 'sessions#destroy'
  get '/auth/failure' => 'sessions#failure'
  get 'confirm_email' => 'users#confirm_email', as: 'confirm_email'

end

app/models/club.rb
# == Schema Information
#
# Table name: clubs
#
#  id           :integer          not null, primary key
#  club_type_id :integer
#  user_id      :integer
#  name         :string
#  description  :text
#  price        :integer
#  phone        :string
#  confirmed    :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Club < ActiveRecord::Base

  include SportObject, ClubSearch

  paginates_per 15

  belongs_to :type, class_name: 'ClubType', foreign_key: 'club_type_id'

  validates :club_type_id, presence: true

  scope :newest, -> {order('created_at DESC')}
  scope :confirmed, ->{ where(confirmed: true) }
  scope :unconfirmed, ->{ where(confirmed: false) }

  def to_param
    "#{id}-#{name.parameterize}"
  end
  
end

app/models/club_type.rb
# == Schema Information
#
# Table name: club_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ClubType < ActiveRecord::Base

  has_many :clubs

  validates :name, presence: true

  default_scope { order('position ASC') }

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  include Locationable
  # helper UsersHelper

  before_action :set_club, only: [ :show, :edit, :update ]
  before_action :check_current_user, only: :new
  before_action :check_club_author, only: :edit
  before_action :set_main_controller

  def index
    if params[:search_by_type].present?
      search_hash = Club.search_by_type(params[:search_by_type])
    elsif params[:search_by_name].present?
      search_hash = Club.search_by_name(params[:search_by_name])
    else
      search_hash = Club.search_confirmed
    end
    @clubs, @message, @map_title = search_hash[:clubs].page(params[:page]), search_hash[:message], search_hash[:map_title]
    @all_clubs = search_hash[:clubs]
    @club_types = ClubType.all
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    respond_to do |format|
      if @location && @club.save
        format.html { redirect_to @club, notice: 'Секція буде додана після проходження модерації' }
      else
        flash[:alert] = 'Поставьте мітку на карті' if @location.nil?
        format.html { render :new }
      end
    end
  end

  def show
    @comments = @club.comments.ordered
    @comment = Comment.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @club.update_attributes(club_params)
        format.html { redirect_to @club, notice: 'До секції були внесені зміни' }
      else
        format.html { render :edit, alert: 'Під час редагуванння виникли помилки' }
      end
    end
  end

  private

  def set_club
    @club = Club.find(params[:id])
  end

  def club_params
    params.require(:club).permit(:name, :club_type_id, :description, :price, :phone)
      .merge(author: current_user, location: @location)
  end

  def check_current_user
    redirect_to root_path, alert: 'Спочатку зареєструйтесь' unless current_user.present?
  end

  def check_club_author
    if (@club.author != current_user) && !current_user.admin?
      redirect_to @club, alert: 'Ви не можете внести зміни до цієї секції'
    end
  end

  def set_main_controller
    session[:main_controller] = 'clubs'
  end

end

app/views/clubs/_form.html.erb
<div class="add_event-page" id="club_form">
    <%= form_for @club, html: { class: 'form' } do |f| %>
        <%= render 'locations/add_location', locationable: @club %>
        <%= hidden_field_tag :location %>
        <ul>
            <li>
                <%= f.label :name, 'Назва' %>
                <%= f.text_field :name, class: "hastip", title: "Обов'язково для заповнення. Довжина більше 5 символів" %>
            </li>
            <li>
                <%= f.label 'Категорія' %>
                <%= select(:club, :club_type_id, ClubType.all.collect { |ct| [ ct.name, ct.id ] }) %>
            </li>
            <li>
                <%= f.label 'Опис' %>
                <%= f.text_area :description, class: "hastip", title: "Обов'язково для заповнення. Довжина більше 20 символів" %>
            </li>
            <li>
                <%= f.label 'Вартість' %>
                <%= f.text_field :price %>
            </li>
            <li>
                <%= f.label 'Контактний номер' %>
                <%= f.text_field :phone, class: "hastip", title: "Обов'язково для заповнення" %>
            </li>
        </ul>
        <%= f.submit 'ОК', class: 'submit-btn' %>
    <% end %>
</div>

app/views/clubs/_search.html.erb
<%= form_tag clubs_path, :method => 'get' do %>
    <p>
        <%= text_field_tag :search_by_name, params[:search_by_name], size: 15 %>
        <%= submit_tag 'Пошук', name: nil %>
    </p>
<% end %>

app/views/clubs/edit.html.erb
<h2>Змінити данні про секцію</h2>
<%= render 'form' %>

app/views/clubs/index.html.erb
<div class="main">
      <%= render 'locations/show_map', locationables: @clubs %>
    <span class="add" ><%= link_to 'Додати секцію', new_club_path if current_user %><br/></span>
    <h2><%= @message %></h2>
    <% @clubs.all.each do |club|%>
        <div class="event">
          <h3><%= link_to club.name, club %></h3>
          <p><%= club.description %></p>
          <span class="author" ><%= link_to club.author.name, club.author %></span>
        </div>
    <% end %>
    <%= paginate @clubs, window: 2 %>
</div>

app/views/clubs/new.html.erb
<h2>Додати секцію</h2><br/>
<%= render 'form' %>

app/views/clubs/show.html.erb
<div class="event-page">
    <div class="event-info" >
        <%= render 'locations/show_location', locationable: @club %>
        <%= link_to 'Редагувати', edit_club_path, class: "edit-event-btn" if user_can_edit?(@club) %>
        <h2><%= @club.name %></h2>
        <span class="no-margin" >
            <%= link_to @club.type.name, clubs_path(search_by_type: @club.type) %>
        </span>
        <p><%= @club.description %></p>
        <ul>
            <li style="float:right">Добавил: <%= link_to @club.author.name, @club.author, class: 'author' %></li>
            <li>Контактный номер: <span style="color:#6495ed;"><%= @club.phone %></span></li>
            <li>Стоимость занятий: <%= @club.price %></li>
        </ul>
    </div>
    <%= link_to 'Перейти до списку всіх секцій', clubs_path %>
    <%= render 'comments/form', commentable: @club %>
    <%= render 'comments/comments' %>
</div>