config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'events#index'

  resources :users do
    post 'send_email_confirmation' => 'users#send_email_confirmation'
  end

  resources :clubs do
    resources :comments
  end

  resources :events do
    resources :comments
  end

  resources :friendships

  # Messages
  resources :messages, only: [:new, :create, :show, :destroy]
  get 'inbox' => 'messages#inbox'
  get 'sentbox' => 'messages#sentbox'
  # Authorization
  post 'login_with_email' => 'sessions#login_with_email'
  get '/auth/:provider/callback' => 'sessions#login_with_oauth'
  post '/auth/:provider/callback' => 'sessions#login_with_oauth'
  # resources :sessions
  get 'logout' => 'sessions#destroy'
  get '/auth/failure' => 'sessions#failure'
  get 'confirm_email' => 'users#confirm_email', as: 'confirm_email'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  provider        :string
#  uid             :string
#  name            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  email           :string
#  about           :text
#  phone           :string
#  skype           :string
#  admin           :boolean          default("f")
#  email_confirmed :boolean          default("f")
#  avatar          :string
#  password_digest :string
#  full_name       :string
#

class User < ActiveRecord::Base

  has_secure_password
  include OmniauthRegistration
  mount_uploader :avatar, AvatarUploader

  acts_as_reader

  has_many :clubs, dependent: :destroy
  has_many :events, dependent: :destroy

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :sent_messages, class_name: 'Message', foreign_key: 'author_id', dependent: :destroy
  has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id', dependent: :destroy

  has_many :confirmations

  before_save :set_password_for_omniuath_users

  validates :name, presence: true, uniqueness: true
  validates :full_name, :skype, allow_blank: true, length: { in: 3..15 }
  validates :email, uniqueness: true, allow_blank: true, email: true
  validates :about, allow_blank: true, length: { in: 0..100 }
  validates :phone, allow_blank: true, length: { in: 6..10 }

  def self.authenticate(email, password)
    user = self.find_by_email(email.downcase)
    user.authenticate(password) if user
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def inbox(page)
    received_messages.where(deleted_by_recipient: false).newest.page(page)
  end

  def sentbox(page)
    sent_messages.where(deleted_by_author: false).newest.page(page)
  end

  def send_email_confirmation(email)
    self.create_confirmation(email: email)
    self.update_attributes(email_confirmed: false)
  end

  def confirm_email(confirmation, code)
    if confirmation.code == code
      update_attributes(email: confirmation.email, email_confirmed: true)
      confirmations.destroy_all
      return true
    else
      return false
    end
  end

  def set_password_for_omniuath_users
    password_digest = SecureRandom.urlsafe_base64 if provider.present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [ :show, :edit, :update ]
  before_action :check_user, only: [ :edit ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @user.send_email_confirmation(@user.email)
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'На вашу електронну адресу було відправлено лист з підтвердженням' }
      else
        format.html { redirect_to root_path, alert: 'При реєстрації виникли помилки' }
      end
    end
  end

  def show
    @user = @user
  end

  def edit
  end

  def update
    if !params[:user][:email].empty? && params[:user][:email] != @user.email
      @user.send_email_confirmation(params[:user][:email])
      notice = 'Профіль був змінений. На вашу електронну адресу було відправлено лист з підтвердженням'
    else
      notice = 'Профіль був змінений.'
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: notice }
      else
        format.html { render :edit }
      end
    end
  end

  def send_email_confirmation
    @user = User.find(params[:id])
    @user.send_email_confirmation(@user.email)
    redirect_to @user, 
      notice: 'На вашу електронну адресу було відправлено лист з підтвердженням'
  end

  def confirm_email
    @confirmation = Confirmation.where(email: params[:email]).last
    @user = User.find(@confirmation.user_id)
    if @user.confirm_email(@confirmation, params[:code])
      redirect_to @user, notice: 'Адресу електронної пошти було підтверджено.'
    else
      redirect_to @user, notice: 'Помилка.'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def check_user
    redirect_to @user, alert: 'У вас немає прав на внесення змін до цього профіля' unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :about, :phone, :skype, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_can_add_to_friends?
    current_user.present? && current_user.id != @user.id && current_user.friends.where(id: @user.id).empty?
  end

  def user_can_remove_from_friends?
    current_user.present? && !current_user.friends.where(id: @user.id).empty?
  end

  def user_can_edit?(obj)
    (current_user == obj.author) || (current_user && current_user.admin?)
  end

  def user_can_send_message_to?(user)
    current_user && (current_user != user)
  end

  def show_email_alert?
    !@user.email.to_s.empty? && @user == current_user
  end
end

app/views/users/edit.html.erb
<div class="edit-usr-page" >
    <%= form_for @user do |f| %>
        <ul>
            <li>
                <%= f.label 'Логин*' %>
                <%= f.text_field :name %>
            </li>
            <li>
                <%= f.label 'Email' %>
                <%= f.text_field :email %>
            </li>
            <li>
                <%= f.label 'Коротко о себе' %>
                <%= f.text_area :about, class: "hastip", title: "Обязательно для заполнения. Длина: от 20 символов" %>
            </li>
            <li>
                <%= f.label 'Номер телефона' %>
                <%= f.text_field :phone, class: "hastip", title: "Длина: от 6 до 10 символов" %>
            </li>
            <li>
                <%= f.label 'Skype' %>
                <%= f.text_field :skype %>
            </li>
            <li>
                <%= f.label 'Загрузить аватар' %>
                <%= f.file_field :avatar, accept: 'image/png,image/gif,image/jpeg' %>
            </li>
        </ul>
        <%= f.submit 'Редактировать', class: "submit-btn" %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="full-profile">
    <%= image_tag avatar_url(@user), class: 'user-photo' %>
    <div class="right-position" >
        <%= link_to 'Редагувати профіль', edit_user_path, class: 'profile-btn' if current_user == @user %>
        <% if user_can_send_message_to?(@user) %>
            <%= link_to 'Відправити повідомлення', new_message_path(recipient_id: @user.id), class: 'profile-btn' %>
        <% end %>
        <%= link_to 'Додати в друзі', friendships_path(friend_id: @user.id), method: :post, class: 'profile-btn' if user_can_add_to_friends? %>
        <%= link_to 'Видалити з друзів', friendship_path(friend_id: @user.id), method: :delete, class: 'profile-btn' if user_can_remove_from_friends? %>
    </div>
    <h2><%= @user.name %></h2>
    <dl class="user-info">
        <dt>Email:</dt>
        <% if @user.email_confirmed? %>
            <dd><%= @user.email %></dd>
        <% elsif show_email_alert? %>
            <dd>
                <%= @user.email %>
                <span class="not-confirmed">
                    <span class="alert"> Увага!</span> Ви не підтвердили адресу елетронної пошти!.<br/>
                    <%= link_to 'Отправить письмо повторно', user_send_email_confirmation_path(@user), method: :post %>
                </span>
            </dd>
        <% else %>
            <dd></dd>
        <% end %>

        <dt>Коротко про себе:</dt>
        <dd><%= @user.about  %></dd>

        <dt>Номер телефону:</dt>
        <dd><%= @user.phone %></dd>

        <dt>Skype:</dt>
        <dd><%= @user.skype %></dd>

        <dt>Друзі:</dt>
        <% if @user.friends.any? %>
            <% @user.friends.each do |friend| %>
                <dd><%= link_to friend.name, friend, class: 'user-friend' %></dd>
            <% end %>
        <% else %>
            <dd>У користувача немає друзів</dd>
        <% end %>

    </dl>
</div>