config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'events#index'

  resources :users do
    post 'send_email_confirmation' => 'users#send_email_confirmation'
  end

  resources :clubs do
    resources :comments
  end

  resources :events do
    resources :comments
  end

  resources :friendships

  # Messages
  resources :messages, only: [:new, :create, :show, :destroy]
  get 'inbox' => 'messages#inbox'
  get 'sentbox' => 'messages#sentbox'
  # Authorization
  post 'login_with_email' => 'sessions#login_with_email'
  get '/auth/:provider/callback' => 'sessions#login_with_oauth'
  post '/auth/:provider/callback' => 'sessions#login_with_oauth'
  # resources :sessions
  get 'logout' => 'sessions#destroy'
  get '/auth/failure' => 'sessions#failure'
  get 'confirm_email' => 'users#confirm_email', as: 'confirm_email'

end

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="geekhub_logo">
        <a href="http://geekhub.ck.ua" class="geekhub" >GeekHub</a>
    </div>
    <p class="copy">&copy 2015, Колесник Сергій, Грігор'єв Дмітрій</p>
</footer>

app/views/shared/_header.html.erb
<header class="header">   <!-- HEADER -->
    <div class="right-position" >
        <% if current_user %>
            <div class="profile">
                <span class="name"><%= current_user.name %><span class="arrow"></span></span>
                <ul class="dropdown">
                    <li><%= link_to 'Профіль', current_user %></li>
                    <li><%= link_to 'Вхідні повідомлення', inbox_path %></li>
                    <li><%= link_to 'Відправлені повідомлення', sentbox_path %></li>
                    <li><%= link_to 'Вихід', logout_path %></li>
                </ul>
            </div>
        <% else %>
            <ul class="log-in">
                <li id="enter" >Вхід</li>
                <li id="register">Реєстрація</li>
            </ul>
        <% end %>
    </div>
        <h1 class="logo">
            <%= link_to image_tag("logo_bg.png"), home_url %>
            SportEvents - спортивні події Черкас
        </h1>
        <%= go_to %>
</header> <!-- HEADER -->
  
<div class="enter-popup">       <!-- POPUP`S -->
    <span class="close">x</span>
    <h3>Вход</h3>
    <%= form_tag 'login_with_email' do %>

        <%= label_tag :email, 'Email' %>
        <%= text_field_tag :email, '', class: "hastip", title: "Обов'язково для заповнення" %>

        <%= label_tag :password, 'Пароль', class: "hastip", title: "Обов'язково для заповнення" %>
        <%= password_field_tag :password %>

        <%= submit_tag 'Войти', class: 'submit-btn' %>
    <% end %>
    <ul class="social-in">
        <li class="vk" ><a href="/auth/vkontakte" title="Вхід за допомогою Вконтакте" ></a></li>
        <li class="tw"><a href="/auth/twitter" title="Вхід за допомогою Twitter" ></a></li>
    </ul>
</div>

<div class="register-popup">
    <span class="close">x</span>
    <h3>Реєстрація</h3>
        <%= form_for User.new do |f| %>

            <%= f.label :name, "Ім'я" %><br>
            <%= f.text_field :name, class: "hastip", title: "Обов'язково для заповнення" %>

            <%= f.label :email, 'Email' %><br>
            <%= f.text_field :email, class: "hastip", title: "Обов'язково для заповнення" %>

            <%= f.label :password, 'Пароль' %><br>
            <%= f.password_field :password, class: "hastip", title: "Обов'язково для заповнення" %>

            <%= f.label :password_confirmation, 'Підтвердження пароля' %><br>
            <%= f.password_field :password_confirmation, class: "hastip", title: "Обов'язково для заповнення" %>

            <%= f.submit 'Зареєструватися', class: 'submit-btn' %>
        <% end %>
</div>

<div class="mask"></div>    <!-- POPUP`S -->

app/views/shared/_sidebar.html.erb
<aside class="sidebar clearfix floating">  <!-- SIDEBAR -->
    <% if current_user %>
        <div class="sidebar-profile" >
            <%= link_to (image_tag avatar_url(current_user), class: 'sidebar-photo'), current_user %>
            <h3><%= current_user.name %></h3>
        </div>
    <% end %>
    <div class="categories">
        <h3>Категорії</h3>
        <ul>
            <% if session[:main_controller] == 'clubs' %>
                <% ClubType.all.each do |ct| %>
                    <li><%= link_to ct.name, clubs_path(search_by_type: ct) %></li>
                <% end %>
            <% else %>
                <% EventType.all.each do |et| %>
                    <li><%= link_to et.name, events_path(search_by_type: et) %><br/></li>
                <% end %>
            <% end %>
        </ul>
    </div>
    <% if session[:main_controller] == 'clubs' %>
        <%= form_tag clubs_path, :method => 'get' do %>
            <%= text_field_tag :search_by_name, params[:search_by_name], class: 'srch-place', placeholder: "ПОШУК..." %>
            <%= submit_tag '', name: nil, class: 'search-btn' %>
        <% end %>
    <% else %>
        <%= form_tag events_path, :method => 'get' do %>
            <%= text_field_tag :search_by_name, params[:search_by_name], class: 'srch-place', placeholder: "ПОШУК..." %>
            <%= submit_tag '', name: nil, class: 'search-btn' %>
        <% end %>
    <% end %>
</aside>          <!-- SIDEBAR -->