config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'events#index'

  resources :users do
    post 'send_email_confirmation' => 'users#send_email_confirmation'
  end

  resources :clubs do
    resources :comments
  end

  resources :events do
    resources :comments
  end

  resources :friendships

  # Messages
  resources :messages, only: [:new, :create, :show, :destroy]
  get 'inbox' => 'messages#inbox'
  get 'sentbox' => 'messages#sentbox'
  # Authorization
  post 'login_with_email' => 'sessions#login_with_email'
  get '/auth/:provider/callback' => 'sessions#login_with_oauth'
  post '/auth/:provider/callback' => 'sessions#login_with_oauth'
  # resources :sessions
  get 'logout' => 'sessions#destroy'
  get '/auth/failure' => 'sessions#failure'
  get 'confirm_email' => 'users#confirm_email', as: 'confirm_email'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id            :integer          not null, primary key
#  event_type_id :integer
#  user_id       :integer
#  name          :string
#  description   :text
#  phone         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  begins_at     :datetime
#

class Event < ActiveRecord::Base

  include SportObject, EventSearch

  acts_as_readable :on => :created_at
  paginates_per 15

  belongs_to :type, class_name: 'EventType', foreign_key: 'event_type_id'

  validates :event_type_id, presence: true
  validates :begins_at, presence: true, date: {
                          after: Proc.new { Time.now },
                          before: Proc.new { Time.now + 1.year },
                          message: 'містить хибне значення'
                        }

  scope :newest, -> { order('created_at DESC') }
  scope :not_started, ->{ where('begins_at > ?', Time.now.to_datetime) }
  scope :started, ->{ where('begins_at < ?', Time.now.to_datetime) }

  # TODO: Update this with to_s method
  def begins_at_show
    begins_at.strftime("%d.%m в %H:%M")
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/models/event_type.rb
# == Schema Information
#
# Table name: event_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EventType < ActiveRecord::Base

  has_many :events

  validates :name, presence: true

  default_scope { order('position ASC') }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  include Locationable
  # helper UsersHelper

  before_action :set_event, only: [ :show, :edit, :update ]
  before_action :check_current_user, only: :new
  before_action :check_event_author, only: :edit
  before_action :set_main_controller

  def index
    if params[:search_by_type].present?
      s_hash = Event.search_by_type(params[:search_by_type])
    elsif params[:search_by_name].present?
      s_hash = Event.search_by_name(params[:search_by_name])
    else
      s_hash = Event.search_not_started
    end
    @events, @message, @map_title = s_hash[:events].page(params[:page]), s_hash[:message], s_hash[:map_title]
    @all_events = s_hash[:events]
    @event_types = EventType.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @location && @event.save
        format.html { redirect_to @event, notice: 'Подія була додана' }
      else
        flash[:alert] = 'Поставьте мітку на карті' if @location.nil?
        format.html { render :new, alert: 'Під час створення події виникли помилки' }
      end
    end
  end

  def show
    @comments = @event.comments.ordered
    @comment = Comment.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @event.update_attributes(event_params)
        format.html { redirect_to @event, notice: 'До секції були внесені зміни' }
      else
        format.html { render :edit, alert: 'Під час редагуванння виникли помилки' }
      end
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :event_type_id, :description, :begins_at, :phone)
      .merge(author: current_user, location: @location)
  end

  def check_current_user
    redirect_to root_path, alert: 'Спочатку зареєструйтесь' unless current_user.present?
  end

  def check_event_author
    if (@event.author != current_user) && !current_user.admin?
      redirect_to @event, alert: 'Ви не можете внести зміни до цієї події'
    end
  end

  def set_main_controller
    session[:main_controller] = 'events'
  end

end

app/helpers/events_helper.rb
module EventsHelper

  def show_date(event)
    date = event.begins_at
    if date.to_date == Date.today
      date.strftime("%H:%M")
    elsif date.to_date == Date.tomorrow
      date.strftime("Завтра, %H:%M")
    else
      date.strftime("%H:%M %m.%d")
    end
  end

end

app/views/events/_form.html.erb
<div class="add_event-page" id="event_form">
    <%= form_for @event, html: { class: 'form' } do |f| %>
        <%= render 'locations/add_location', locationable: @event %>
        <%= hidden_field_tag :location %>
        <ul>
            <li>
                <%= f.label :name, 'Назва' %>
                <%= f.text_field :name, class: "hastip", title: "Обов'язково для заповнення. Довжина більше 5 символів" %>
            </li>
            <li>
                <%= f.label 'Категорія' %>
                <%= select(:event, :event_type_id, EventType.all.collect { |et| [ et.name, et.id ] }) %>
            </li>
            <li>
                <%= f.label 'Опис' %>
                <%= f.text_area :description, class: "hastip", title: "Обов'язково для заповнення. Довжина більше 20 символів" %>
            </li>
            <li class="date">
                <%= f.label 'Початок' %>
                <%= f.datetime_select :begins_at, default: 26.hours.from_now, start_year: 2015, end_year: 2015 %>
            </li>
            <li>
                <%= f.label 'Контактний номер' %>
                <%= f.text_field :phone, class: "hastip", title: "Обязательно для заполнения." %>
            </li>
        </ul>
        <%= f.submit 'ОК', class: 'submit-btn' %>
    <% end %>
</div>

app/views/events/_search.html.erb
<%= form_tag events_path, :method => 'get' do %>
    <p>
        <%= text_field_tag :search_by_name, params[:search_by_name], size: 15 %>
        <%= submit_tag 'Пошук', name: nil %>
    </p>
<% end %>

app/views/events/edit.html.erb
<h2>Змінити дані про подію</h2>
<%= render 'form' %>

app/views/events/index.html.erb
<div class="main">
    <%= render 'locations/show_map', locationables: @events %>
    <span class="add" ><%= link_to 'Додати подію', new_event_path if current_user %><br/></span>
    <h2><%= @message %></h2>
    <% @events.all.each do |event|%>
        <div class="event">
            <h3><%= link_to event.name, event %></h3>
            <p><%= event.description %></p>
            <span class="date">Початок: <%= show_date(event) %></span>
            <span class="author" ><%= link_to event.author.name, event.author %></span>
        </div>
    <% end %>
    <%= paginate @events, window: 2 %>
</div>

app/views/events/new.html.erb
<h2>Додати подію</h2><br/>
<%= render 'form' %>

app/views/events/show.html.erb
<div class="event-page">
        <div class="event-info" >
          <%= render 'locations/show_location', locationable: @event %>
          <%= link_to 'Редактировать', edit_event_path, class: "edit-event-btn" if user_can_edit?(@event) %>
          <h2><%= @event.name %></h2>
          <span class="no-margin" >
            <%= link_to @event.type.name, events_path(search_by_type: @event.type) %>
          </span>
          <p><%= @event.description %></p>
          <ul>
            <li>Контактный номер: <span style="color:#6495ed;"><%= @event.phone %></span></li>
            <li style="float:right">Добавил: <%= link_to @event.author.name, @event.author, class: 'author' %></li>
            <li class="time" >Начало: <%= show_date(@event) %></li>
          </ul>
        </div>
        <%= link_to 'Перейти к списку всех событий', events_path %>
        <%= render 'comments/form', commentable: @event %>
        <%= render 'comments/comments' %>
</div>